version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/node"
        versions:
          - ">=13"
      - dependency-name: "@types/vscode"
        versions:
          - ">=1.47"
    open-pull-requests-limit: 15
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
